import type { KuroshiroNotation } from "@services/FuriganaService/kuroshiro";
import { flatKuroshiroNotation } from "./flatKuroshiroNotation";

describe("FuriganaService", () => {
  it("should merge characters with no reading as string", () => {
    // すべての人間は、生まれながらにして自由であり、かつ、尊厳と権利とについて平等である。
    const kuroshiroOutput: KuroshiroNotation[] = [
      {
        surfaceForm: "す",
        type: "mixed",
        pronunciation: "ス",
        token: {
          word_id: 34890,
          word_type: "KNOWN",
          word_position: 1,
          surface_form: "すべて",
          pos: "名詞",
          pos_detail_1: "副詞可能",
          pos_detail_2: "*",
          pos_detail_3: "*",
          conjugated_type: "*",
          conjugated_form: "*",
          basic_form: "すべて",
          reading: "スベテ",
          pronunciation: "スベテ",
        },
      },
      {
        surfaceForm: "べ",
        type: "mixed",
        pronunciation: "ベ",
        token: {
          word_id: 34890,
          word_type: "KNOWN",
          word_position: 1,
          surface_form: "すべて",
          pos: "名詞",
          pos_detail_1: "副詞可能",
          pos_detail_2: "*",
          pos_detail_3: "*",
          conjugated_type: "*",
          conjugated_form: "*",
          basic_form: "すべて",
          reading: "スベテ",
          pronunciation: "スベテ",
        },
      },
      {
        surfaceForm: "て",
        type: "mixed",
        pronunciation: "テ",
        token: {
          word_id: 34890,
          word_type: "KNOWN",
          word_position: 1,
          surface_form: "すべて",
          pos: "名詞",
          pos_detail_1: "副詞可能",
          pos_detail_2: "*",
          pos_detail_3: "*",
          conjugated_type: "*",
          conjugated_form: "*",
          basic_form: "すべて",
          reading: "スベテ",
          pronunciation: "スベテ",
        },
      },
      {
        surfaceForm: "の",
        type: "mixed",
        pronunciation: "ノ",
        token: {
          word_id: 93100,
          word_type: "KNOWN",
          word_position: 4,
          surface_form: "の",
          pos: "助詞",
          pos_detail_1: "連体化",
          pos_detail_2: "*",
          pos_detail_3: "*",
          conjugated_type: "*",
          conjugated_form: "*",
          basic_form: "の",
          reading: "ノ",
          pronunciation: "ノ",
        },
      },
      {
        surfaceForm: "人間",
        type: "kanji",
        reading: "にんげん",
        pronunciation: "ニンゲン",
        token: {
          word_id: 2712780,
          word_type: "KNOWN",
          word_position: 5,
          surface_form: "人間",
          pos: "名詞",
          pos_detail_1: "一般",
          pos_detail_2: "*",
          pos_detail_3: "*",
          conjugated_type: "*",
          conjugated_form: "*",
          basic_form: "人間",
          reading: "ニンゲン",
          pronunciation: "ニンゲン",
        },
      },
      {
        surfaceForm: "は",
        type: "mixed",
        pronunciation: "ワ",
        token: {
          word_id: 93010,
          word_type: "KNOWN",
          word_position: 7,
          surface_form: "は",
          pos: "助詞",
          pos_detail_1: "係助詞",
          pos_detail_2: "*",
          pos_detail_3: "*",
          conjugated_type: "*",
          conjugated_form: "*",
          basic_form: "は",
          reading: "ハ",
          pronunciation: "ワ",
        },
      },
      {
        surfaceForm: "、",
        type: "others",
        reading: "、",
        pronunciation: "、",
        token: {
          word_id: 90910,
          word_type: "KNOWN",
          word_position: 8,
          surface_form: "、",
          pos: "記号",
          pos_detail_1: "読点",
          pos_detail_2: "*",
          pos_detail_3: "*",
          conjugated_type: "*",
          conjugated_form: "*",
          basic_form: "、",
          reading: "、",
          pronunciation: "、",
        },
      },
      {
        surfaceForm: "生",
        type: "kanji",
        reading: "う",
        pronunciation: "ウ",
        token: {
          word_id: 179630,
          word_type: "KNOWN",
          word_position: 9,
          surface_form: "生まれながら",
          pos: "副詞",
          pos_detail_1: "助詞類接続",
          pos_detail_2: "*",
          pos_detail_3: "*",
          conjugated_type: "*",
          conjugated_form: "*",
          basic_form: "生まれながら",
          reading: "ウマレナガラ",
          pronunciation: "ウマレナガラ",
        },
      },
      {
        surfaceForm: "ま",
        type: "mixed",
        reading: "ま",
        pronunciation: "マ",
        token: {
          word_id: 179630,
          word_type: "KNOWN",
          word_position: 9,
          surface_form: "生まれながら",
          pos: "副詞",
          pos_detail_1: "助詞類接続",
          pos_detail_2: "*",
          pos_detail_3: "*",
          conjugated_type: "*",
          conjugated_form: "*",
          basic_form: "生まれながら",
          reading: "ウマレナガラ",
          pronunciation: "ウマレナガラ",
        },
      },
      {
        surfaceForm: "れ",
        type: "mixed",
        reading: "れ",
        pronunciation: "レ",
        token: {
          word_id: 179630,
          word_type: "KNOWN",
          word_position: 9,
          surface_form: "生まれながら",
          pos: "副詞",
          pos_detail_1: "助詞類接続",
          pos_detail_2: "*",
          pos_detail_3: "*",
          conjugated_type: "*",
          conjugated_form: "*",
          basic_form: "生まれながら",
          reading: "ウマレナガラ",
          pronunciation: "ウマレナガラ",
        },
      },
      {
        surfaceForm: "な",
        type: "mixed",
        reading: "な",
        pronunciation: "ナ",
        token: {
          word_id: 179630,
          word_type: "KNOWN",
          word_position: 9,
          surface_form: "生まれながら",
          pos: "副詞",
          pos_detail_1: "助詞類接続",
          pos_detail_2: "*",
          pos_detail_3: "*",
          conjugated_type: "*",
          conjugated_form: "*",
          basic_form: "生まれながら",
          reading: "ウマレナガラ",
          pronunciation: "ウマレナガラ",
        },
      },
      {
        surfaceForm: "が",
        type: "mixed",
        reading: "が",
        pronunciation: "ガ",
        token: {
          word_id: 179630,
          word_type: "KNOWN",
          word_position: 9,
          surface_form: "生まれながら",
          pos: "副詞",
          pos_detail_1: "助詞類接続",
          pos_detail_2: "*",
          pos_detail_3: "*",
          conjugated_type: "*",
          conjugated_form: "*",
          basic_form: "生まれながら",
          reading: "ウマレナガラ",
          pronunciation: "ウマレナガラ",
        },
      },
      {
        surfaceForm: "ら",
        type: "mixed",
        reading: "ら",
        pronunciation: "ラ",
        token: {
          word_id: 179630,
          word_type: "KNOWN",
          word_position: 9,
          surface_form: "生まれながら",
          pos: "副詞",
          pos_detail_1: "助詞類接続",
          pos_detail_2: "*",
          pos_detail_3: "*",
          conjugated_type: "*",
          conjugated_form: "*",
          basic_form: "生まれながら",
          reading: "ウマレナガラ",
          pronunciation: "ウマレナガラ",
        },
      },
      {
        surfaceForm: "に",
        type: "mixed",
        pronunciation: "ニ",
        token: {
          word_id: 92030,
          word_type: "KNOWN",
          word_position: 15,
          surface_form: "に",
          pos: "助詞",
          pos_detail_1: "格助詞",
          pos_detail_2: "一般",
          pos_detail_3: "*",
          conjugated_type: "*",
          conjugated_form: "*",
          basic_form: "に",
          reading: "ニ",
          pronunciation: "ニ",
        },
      },
      {
        surfaceForm: "し",
        type: "mixed",
        pronunciation: "シ",
        token: {
          word_id: 3011810,
          word_type: "KNOWN",
          word_position: 16,
          surface_form: "し",
          pos: "動詞",
          pos_detail_1: "自立",
          pos_detail_2: "*",
          pos_detail_3: "*",
          conjugated_type: "サ変・スル",
          conjugated_form: "連用形",
          basic_form: "する",
          reading: "シ",
          pronunciation: "シ",
        },
      },
      {
        surfaceForm: "て",
        type: "mixed",
        pronunciation: "テ",
        token: {
          word_id: 92780,
          word_type: "KNOWN",
          word_position: 17,
          surface_form: "て",
          pos: "助詞",
          pos_detail_1: "接続助詞",
          pos_detail_2: "*",
          pos_detail_3: "*",
          conjugated_type: "*",
          conjugated_form: "*",
          basic_form: "て",
          reading: "テ",
          pronunciation: "テ",
        },
      },
      {
        surfaceForm: "自由",
        type: "kanji",
        reading: "じゆう",
        pronunciation: "ジユー",
        token: {
          word_id: 307680,
          word_type: "KNOWN",
          word_position: 18,
          surface_form: "自由",
          pos: "名詞",
          pos_detail_1: "形容動詞語幹",
          pos_detail_2: "*",
          pos_detail_3: "*",
          conjugated_type: "*",
          conjugated_form: "*",
          basic_form: "自由",
          reading: "ジユウ",
          pronunciation: "ジユー",
        },
      },
      {
        surfaceForm: "で",
        type: "mixed",
        pronunciation: "デ",
        token: {
          word_id: 23710,
          word_type: "KNOWN",
          word_position: 20,
          surface_form: "で",
          pos: "助動詞",
          pos_detail_1: "*",
          pos_detail_2: "*",
          pos_detail_3: "*",
          conjugated_type: "特殊・ダ",
          conjugated_form: "連用形",
          basic_form: "だ",
          reading: "デ",
          pronunciation: "デ",
        },
      },
      {
        surfaceForm: "あ",
        type: "mixed",
        pronunciation: "ア",
        token: {
          word_id: 24330,
          word_type: "KNOWN",
          word_position: 21,
          surface_form: "あり",
          pos: "助動詞",
          pos_detail_1: "*",
          pos_detail_2: "*",
          pos_detail_3: "*",
          conjugated_type: "五段・ラ行アル",
          conjugated_form: "連用形",
          basic_form: "ある",
          reading: "アリ",
          pronunciation: "アリ",
        },
      },
      {
        surfaceForm: "り",
        type: "mixed",
        pronunciation: "リ",
        token: {
          word_id: 24330,
          word_type: "KNOWN",
          word_position: 21,
          surface_form: "あり",
          pos: "助動詞",
          pos_detail_1: "*",
          pos_detail_2: "*",
          pos_detail_3: "*",
          conjugated_type: "五段・ラ行アル",
          conjugated_form: "連用形",
          basic_form: "ある",
          reading: "アリ",
          pronunciation: "アリ",
        },
      },
      {
        surfaceForm: "、",
        type: "others",
        reading: "、",
        pronunciation: "、",
        token: {
          word_id: 90910,
          word_type: "KNOWN",
          word_position: 23,
          surface_form: "、",
          pos: "記号",
          pos_detail_1: "読点",
          pos_detail_2: "*",
          pos_detail_3: "*",
          conjugated_type: "*",
          conjugated_form: "*",
          basic_form: "、",
          reading: "、",
          pronunciation: "、",
        },
      },
      {
        surfaceForm: "か",
        type: "mixed",
        pronunciation: "カ",
        token: {
          word_id: 14040,
          word_type: "KNOWN",
          word_position: 24,
          surface_form: "かつ",
          pos: "接続詞",
          pos_detail_1: "*",
          pos_detail_2: "*",
          pos_detail_3: "*",
          conjugated_type: "*",
          conjugated_form: "*",
          basic_form: "かつ",
          reading: "カツ",
          pronunciation: "カツ",
        },
      },
      {
        surfaceForm: "つ",
        type: "mixed",
        pronunciation: "ツ",
        token: {
          word_id: 14040,
          word_type: "KNOWN",
          word_position: 24,
          surface_form: "かつ",
          pos: "接続詞",
          pos_detail_1: "*",
          pos_detail_2: "*",
          pos_detail_3: "*",
          conjugated_type: "*",
          conjugated_form: "*",
          basic_form: "かつ",
          reading: "カツ",
          pronunciation: "カツ",
        },
      },
      {
        surfaceForm: "、",
        type: "others",
        reading: "、",
        pronunciation: "、",
        token: {
          word_id: 90910,
          word_type: "KNOWN",
          word_position: 26,
          surface_form: "、",
          pos: "記号",
          pos_detail_1: "読点",
          pos_detail_2: "*",
          pos_detail_3: "*",
          conjugated_type: "*",
          conjugated_form: "*",
          basic_form: "、",
          reading: "、",
          pronunciation: "、",
        },
      },
      {
        surfaceForm: "尊厳",
        type: "kanji",
        reading: "そんげん",
        pronunciation: "ソンゲン",
        token: {
          word_id: 2205240,
          word_type: "KNOWN",
          word_position: 27,
          surface_form: "尊厳",
          pos: "名詞",
          pos_detail_1: "一般",
          pos_detail_2: "*",
          pos_detail_3: "*",
          conjugated_type: "*",
          conjugated_form: "*",
          basic_form: "尊厳",
          reading: "ソンゲン",
          pronunciation: "ソンゲン",
        },
      },
      {
        surfaceForm: "と",
        type: "mixed",
        pronunciation: "ト",
        token: {
          word_id: 93120,
          word_type: "KNOWN",
          word_position: 29,
          surface_form: "と",
          pos: "助詞",
          pos_detail_1: "並立助詞",
          pos_detail_2: "*",
          pos_detail_3: "*",
          conjugated_type: "*",
          conjugated_form: "*",
          basic_form: "と",
          reading: "ト",
          pronunciation: "ト",
        },
      },
      {
        surfaceForm: "権利",
        type: "kanji",
        reading: "けんり",
        pronunciation: "ケンリ",
        token: {
          word_id: 2391740,
          word_type: "KNOWN",
          word_position: 30,
          surface_form: "権利",
          pos: "名詞",
          pos_detail_1: "一般",
          pos_detail_2: "*",
          pos_detail_3: "*",
          conjugated_type: "*",
          conjugated_form: "*",
          basic_form: "権利",
          reading: "ケンリ",
          pronunciation: "ケンリ",
        },
      },
      {
        surfaceForm: "と",
        type: "mixed",
        pronunciation: "ト",
        token: {
          word_id: 93120,
          word_type: "KNOWN",
          word_position: 32,
          surface_form: "と",
          pos: "助詞",
          pos_detail_1: "並立助詞",
          pos_detail_2: "*",
          pos_detail_3: "*",
          conjugated_type: "*",
          conjugated_form: "*",
          basic_form: "と",
          reading: "ト",
          pronunciation: "ト",
        },
      },
      {
        surfaceForm: "に",
        type: "mixed",
        pronunciation: "ニ",
        token: {
          word_id: 80520,
          word_type: "KNOWN",
          word_position: 33,
          surface_form: "について",
          pos: "助詞",
          pos_detail_1: "格助詞",
          pos_detail_2: "連語",
          pos_detail_3: "*",
          conjugated_type: "*",
          conjugated_form: "*",
          basic_form: "について",
          reading: "ニツイテ",
          pronunciation: "ニツイテ",
        },
      },
      {
        surfaceForm: "つ",
        type: "mixed",
        pronunciation: "ツ",
        token: {
          word_id: 80520,
          word_type: "KNOWN",
          word_position: 33,
          surface_form: "について",
          pos: "助詞",
          pos_detail_1: "格助詞",
          pos_detail_2: "連語",
          pos_detail_3: "*",
          conjugated_type: "*",
          conjugated_form: "*",
          basic_form: "について",
          reading: "ニツイテ",
          pronunciation: "ニツイテ",
        },
      },
      {
        surfaceForm: "い",
        type: "mixed",
        pronunciation: "イ",
        token: {
          word_id: 80520,
          word_type: "KNOWN",
          word_position: 33,
          surface_form: "について",
          pos: "助詞",
          pos_detail_1: "格助詞",
          pos_detail_2: "連語",
          pos_detail_3: "*",
          conjugated_type: "*",
          conjugated_form: "*",
          basic_form: "について",
          reading: "ニツイテ",
          pronunciation: "ニツイテ",
        },
      },
      {
        surfaceForm: "て",
        type: "mixed",
        pronunciation: "テ",
        token: {
          word_id: 80520,
          word_type: "KNOWN",
          word_position: 33,
          surface_form: "について",
          pos: "助詞",
          pos_detail_1: "格助詞",
          pos_detail_2: "連語",
          pos_detail_3: "*",
          conjugated_type: "*",
          conjugated_form: "*",
          basic_form: "について",
          reading: "ニツイテ",
          pronunciation: "ニツイテ",
        },
      },
      {
        surfaceForm: "平等",
        type: "kanji",
        reading: "びょうどう",
        pronunciation: "ビョードー",
        token: {
          word_id: 20670,
          word_type: "KNOWN",
          word_position: 37,
          surface_form: "平等",
          pos: "名詞",
          pos_detail_1: "形容動詞語幹",
          pos_detail_2: "*",
          pos_detail_3: "*",
          conjugated_type: "*",
          conjugated_form: "*",
          basic_form: "平等",
          reading: "ビョウドウ",
          pronunciation: "ビョードー",
        },
      },
      {
        surfaceForm: "で",
        type: "mixed",
        pronunciation: "デ",
        token: {
          word_id: 23710,
          word_type: "KNOWN",
          word_position: 39,
          surface_form: "で",
          pos: "助動詞",
          pos_detail_1: "*",
          pos_detail_2: "*",
          pos_detail_3: "*",
          conjugated_type: "特殊・ダ",
          conjugated_form: "連用形",
          basic_form: "だ",
          reading: "デ",
          pronunciation: "デ",
        },
      },
      {
        surfaceForm: "あ",
        type: "mixed",
        pronunciation: "ア",
        token: {
          word_id: 24300,
          word_type: "KNOWN",
          word_position: 40,
          surface_form: "ある",
          pos: "助動詞",
          pos_detail_1: "*",
          pos_detail_2: "*",
          pos_detail_3: "*",
          conjugated_type: "五段・ラ行アル",
          conjugated_form: "基本形",
          basic_form: "ある",
          reading: "アル",
          pronunciation: "アル",
        },
      },
      {
        surfaceForm: "る",
        type: "mixed",
        pronunciation: "ル",
        token: {
          word_id: 24300,
          word_type: "KNOWN",
          word_position: 40,
          surface_form: "ある",
          pos: "助動詞",
          pos_detail_1: "*",
          pos_detail_2: "*",
          pos_detail_3: "*",
          conjugated_type: "五段・ラ行アル",
          conjugated_form: "基本形",
          basic_form: "ある",
          reading: "アル",
          pronunciation: "アル",
        },
      },
      {
        surfaceForm: "。",
        type: "others",
        reading: "。",
        pronunciation: "。",
        token: {
          word_id: 90940,
          word_type: "KNOWN",
          word_position: 42,
          surface_form: "。",
          pos: "記号",
          pos_detail_1: "句点",
          pos_detail_2: "*",
          pos_detail_3: "*",
          conjugated_type: "*",
          conjugated_form: "*",
          basic_form: "。",
          reading: "。",
          pronunciation: "。",
        },
      },
    ];
    const flatten = flatKuroshiroNotation(kuroshiroOutput);

    expect(flatten).toEqual([
      "すべての",
      {
        text: "人間",
        reading: "にんげん",
        basicForm: "人間",
      },
      "は、",
      {
        text: "生",
        reading: "う",
        basicForm: "生まれながら",
      },
      "まれながらにして",
      {
        text: "自由",
        reading: "じゆう",
        basicForm: "自由",
      },
      "であり、かつ、",
      {
        text: "尊厳",
        reading: "そんげん",
        basicForm: "尊厳",
      },
      "と",
      {
        text: "権利",
        reading: "けんり",
        basicForm: "権利",
      },
      "とについて",
      {
        text: "平等",
        reading: "びょうどう",
        basicForm: "平等",
      },
      "である。",
    ]);
  });
});
